# Generated by Django 5.2.5 on 2025-08-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('movilidad', 'Movilidad')], max_length=20)),
                ('grupo_muscular', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
