# Generated by Django 5.2.5 on 2025-08-29 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('grasa_corporal', models.FloatField(blank=True, null=True)),
                ('medida_cintura', models.FloatField(blank=True, null=True)),
                ('medida_brazo', models.FloatField(blank=True, null=True)),
                ('medida_pierna', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
